// =============================================================
// am-trade-management — Industry-Grade k6 SPT Test Suite
// Version: 2.0 (fixes all issues from v1)
//
// USAGE:
//   # Phase 1 – Baseline
//   k6 run --env SCENARIO=baseline --env AUTH_URL=... --env TEST_USER_ID=spt-user-1 spt-test.js
//
//   # Phase 2 – Load
//   k6 run --env SCENARIO=load --env AUTH_URL=... --env TEST_USER_ID=spt-user-1 spt-test.js
//
//   # Phase 3 – Stress
//   k6 run --env SCENARIO=stress --env AUTH_URL=... --env TEST_USER_ID=spt-user-1 spt-test.js
//
//   # Phase 4 – Soak
//   k6 run --env SCENARIO=soak --env AUTH_URL=... --env TEST_USER_ID=spt-user-1 spt-test.js
//
//   # Phase 5 – Mixed R/W
//   k6 run --env SCENARIO=mixed --env AUTH_URL=... --env TEST_USER_ID=spt-user-1 spt-test.js
//
// REQUIRED ENV VARS:
//   AUTH_URL         – Full URL to get a JWT token (your identity service login endpoint)
//   AUTH_USERNAME    – Test user username for auth service
//   AUTH_PASSWORD    – Test user password for auth service
//   TEST_USER_ID     – One of the spt-user-{n} IDs created by seed-data.js
//   SCENARIO         – Which test to run: baseline | load | stress | soak | mixed
//
// OUTPUT:
//   k6 run ... --out json=results/baseline.json spt-test.js
// =============================================================

import http from 'k6/http';
import { sleep, check, group, fail } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// =============================================================
// SECTION 1: CONFIGURATION
// =============================================================

const BASE_URL    = __ENV.BASE_URL    || 'https://am-dev.asrax.in';
const AUTH_URL    = __ENV.AUTH_URL;   // REQUIRED — no fallback to force explicit config
const AUTH_USER   = __ENV.AUTH_USERNAME;
const AUTH_PASS   = __ENV.AUTH_PASSWORD;
const TEST_USER   = __ENV.TEST_USER_ID || 'spt-user-1';
const SCENARIO    = __ENV.SCENARIO    || 'baseline';

// Validate required config at startup (prevents silent failures)
if (!AUTH_URL)  fail('AUTH_URL env var is required. Set it with --env AUTH_URL=https://...');
if (!AUTH_USER) fail('AUTH_USERNAME env var is required.');
if (!AUTH_PASS) fail('AUTH_PASSWORD env var is required.');

// Portfolio IDs generated by seed-data.js — 10 users * 2 portfolios each.
// Each VU picks a different one (round-robin by VU index) so we avoid
// hammering the same MongoDB document and artificially warming its page cache.
const PORTFOLIO_IDS = new SharedArray('portfolios', function() {
  return [
    'spt-portfolio-1-1', 'spt-portfolio-1-2',
    'spt-portfolio-2-1', 'spt-portfolio-2-2',
    'spt-portfolio-3-1', 'spt-portfolio-3-2',
    'spt-portfolio-4-1', 'spt-portfolio-4-2',
    'spt-portfolio-5-1', 'spt-portfolio-5-2',
    'spt-portfolio-6-1', 'spt-portfolio-6-2',
    'spt-portfolio-7-1', 'spt-portfolio-7-2',
    'spt-portfolio-8-1', 'spt-portfolio-8-2',
    'spt-portfolio-9-1', 'spt-portfolio-9-2',
    'spt-portfolio-10-1','spt-portfolio-10-2',
  ];
});

// =============================================================
// SECTION 2: CUSTOM METRICS
// (true = record min/max/avg/p50/p90/p95/p99 per metric)
// =============================================================

const errorRate            = new Rate('spt_error_rate');
const portfolioSummaryTime = new Trend('spt_portfolio_summary_ms', true);
const tradeDetailsTime     = new Trend('spt_trade_details_ms', true);
const tradeSummaryTime     = new Trend('spt_trade_summary_ms', true);
const filterTime           = new Trend('spt_filter_trades_ms', true);
const calendarDayTime      = new Trend('spt_calendar_day_ms', true);
const writeTradeTime       = new Trend('spt_write_trade_ms', true);
const totalErrors          = new Counter('spt_total_errors');

// =============================================================
// SECTION 3: PASS/FAIL THRESHOLDS (SLOs)
// These are the numbers that make or break the test result.
// Based on: P99 should be < 2s for reads, < 3s for writes.
// Error rate must stay under 1% for the entire run.
// =============================================================

const THRESHOLDS = {
  // Global: all requests combined
  'http_req_duration':             ['p(95)<2000', 'p(99)<3000'],
  // Per-endpoint SLOs
  'spt_portfolio_summary_ms':      ['p(95)<800',  'p(99)<1500'],
  'spt_trade_details_ms':          ['p(95)<1200', 'p(99)<2000'],
  'spt_trade_summary_ms':          ['p(95)<1500', 'p(99)<2500'],
  'spt_filter_trades_ms':          ['p(95)<1200', 'p(99)<2000'],
  'spt_calendar_day_ms':           ['p(95)<1000', 'p(99)<1800'],
  'spt_write_trade_ms':            ['p(95)<1500', 'p(99)<3000'],
  // Error rate: < 1% for load test, < 5% for stress test
  'spt_error_rate':                ['rate<0.01'],
  // Zero total errors allowed in baseline
  'http_req_failed':               ['rate<0.01'],
};

// =============================================================
// SECTION 4: SCENARIOS
// Switch between them via --env SCENARIO=<name>
// =============================================================

const SCENARIOS = {

  // ──────────────────────────────────────────────────────────
  // PHASE 1: BASELINE
  // Goal: raw single-user P99. Zero concurrency noise.
  // ──────────────────────────────────────────────────────────
  baseline: {
    executor: 'constant-vus',
    vus: 1,
    duration: '5m',   // Long enough for JVM to JIT-compile the hot paths
    gracefulStop: '30s',
    tags: { scenario: 'baseline' },
  },

  // ──────────────────────────────────────────────────────────
  // PHASE 2: LOAD TEST
  // Goal: steady expected load. Ramp up slowly (avoids cold shock).
  // VU derivation: 500 DAU × 3 sessions/day × 3min/session / 1440 min ≈ 3 concurrent
  //               × 15 headroom = ~50 VUs is a reasonable upper estimate.
  // ──────────────────────────────────────────────────────────
  load: {
    executor: 'ramping-vus',
    startVUs: 1,
    stages: [
      { duration: '3m',  target: 10 }, // Warm-up: let JVM JIT-compile under light load
      { duration: '5m',  target: 25 }, // Normal load
      { duration: '7m',  target: 50 }, // Peak load — hold and observe
      { duration: '5m',  target: 50 }, // Sustain peak — check for latency creep
      { duration: '3m',  target: 0  }, // Cool down
    ],
    gracefulRampDown: '1m',
    tags: { scenario: 'load' },
  },

  // ──────────────────────────────────────────────────────────
  // PHASE 3: STRESS TEST
  // Goal: find exact breaking point. Tomcat max-threads = 200.
  // We push through it to see what happens at 250+.
  // ──────────────────────────────────────────────────────────
  stress: {
    executor: 'ramping-vus',
    startVUs: 5,
    stages: [
      { duration: '3m',  target: 50  }, // Warm up
      { duration: '3m',  target: 100 }, // 2× normal — watch MongoDB connections
      { duration: '3m',  target: 150 }, // 3× — Tomcat threads will start queuing
      { duration: '3m',  target: 200 }, // AT the thread limit — expect latency spike
      { duration: '3m',  target: 250 }, // BEYOND limit — expect 503/timeouts
      { duration: '3m',  target: 300 }, // Full failure mode — note exact VU of collapse
      { duration: '3m',  target: 0   }, // Recover — confirm service bounces back
    ],
    gracefulRampDown: '1m',
    tags: { scenario: 'stress' },
  },

  // ──────────────────────────────────────────────────────────
  // PHASE 4: SOAK TEST (Endurance)
  // Goal: detect memory leaks over extended time.
  // Spring Boot JVM can leak if objects are not GC'd. This catches it.
  // Run at night — it takes 90 minutes.
  // ──────────────────────────────────────────────────────────
  soak: {
    executor: 'constant-vus',
    vus: 20,
    duration: '90m',  // MUST be long — leaks only appear over time
    gracefulStop: '2m',
    tags: { scenario: 'soak' },
  },

  // ──────────────────────────────────────────────────────────
  // PHASE 5: MIXED READ + WRITE
  // Goal: find MongoDB write/read lock contention.
  // 80% reads, 20% writes — realistic production mix.
  // ──────────────────────────────────────────────────────────
  mixed: {
    executor: 'ramping-vus',
    startVUs: 5,
    stages: [
      { duration: '3m',  target: 30 },
      { duration: '10m', target: 30 }, // Sustained mixed load
      { duration: '2m',  target: 0  },
    ],
    gracefulRampDown: '1m',
    tags: { scenario: 'mixed' },
  },
};

export const options = {
  thresholds: THRESHOLDS,
  scenarios: { [SCENARIO]: SCENARIOS[SCENARIO] },
};

// =============================================================
// SECTION 5: PER-VU STATE (Token Refresh)
//
// Each VU manages its own JWT token and refreshes it BEFORE it
// expires. This prevents 401 errors during long tests (soak, load).
//
// TOKEN_REFRESH_MARGIN_MS = refresh the token 2 minutes before
// the service would reject it.
// =============================================================

const TOKEN_REFRESH_MARGIN_MS = 2 * 60 * 1000; // 2 minutes

let _vuToken = null;
let _vuTokenExpiresAt = 0;

function getValidToken() {
  const now = Date.now();

  if (_vuToken && now < (_vuTokenExpiresAt - TOKEN_REFRESH_MARGIN_MS)) {
    return _vuToken; // Token is still fresh — reuse it
  }

  // Token is expired or about to expire — fetch a new one
  const authPayload = JSON.stringify({
    username: AUTH_USER,
    password: AUTH_PASS,
  });

  const res = http.post(AUTH_URL, authPayload, {
    headers: { 'Content-Type': 'application/json' },
    tags: { endpoint: 'auth' },
  });

  const ok = check(res, {
    'auth: status 200': (r) => r.status === 200,
    'auth: token in body': (r) => {
      try { return JSON.parse(r.body).accessToken !== undefined; } catch { return false; }
    },
  });

  if (!ok) {
    fail(`Authentication failed for VU ${__VU}. Status: ${res.status}. Body: ${res.body}`);
  }

  const body = JSON.parse(res.body);
  _vuToken = body.accessToken;

  // The token TTL in seconds is typically in `expires_in` or `expiresIn`.
  // Default to 14 minutes if the field isn't present.
  const ttlSeconds = body.expires_in || body.expiresIn || (14 * 60);
  _vuTokenExpiresAt = now + (ttlSeconds * 1000);

  return _vuToken;
}

// =============================================================
// SECTION 6: REQUEST HELPERS
// =============================================================

function authHeaders() {
  return {
    'Authorization': `Bearer ${getValidToken()}`,
    'Content-Type': 'application/json',
    'Accept': 'application/json',
  };
}

// Randomised think time: between 1 and 5 seconds, non-uniform.
// Uses Math.random() so VUs don't synchronise into bursts.
function thinkTime() {
  sleep(1 + Math.random() * 4);
}

// Short think time for back-to-back reads within the same user flow
function shortThink() {
  sleep(0.2 + Math.random() * 0.8);
}

// Each VU gets a different portfolio so MongoDB doesn't warm up
// the same document page for all VUs.
function getPortfolioId() {
  return PORTFOLIO_IDS[(__VU - 1) % PORTFOLIO_IDS.length];
}

function checkAndRecord(res, checks, trendMetric, label) {
  const passed = check(res, checks);
  trendMetric.add(res.timings.duration);
  if (!passed) {
    errorRate.add(1);
    totalErrors.add(1);
    console.warn(`FAIL [${label}] status=${res.status} duration=${res.timings.duration}ms`);
  } else {
    errorRate.add(0);
  }
}

// =============================================================
// SECTION 7: USER FLOWS
// Each flow simulates a realistic sequence of actions a real
// user would take in one session (not just one endpoint).
// =============================================================

function flowDashboardLoad(portfolioId) {
  // A user opens the app. The dashboard fires these 2 requests in order.
  group('Flow: Dashboard Load', () => {
    // 1. Portfolio summary (the main data fetch)
    const r1 = http.get(`${BASE_URL}/v1/portfolio-summary/by-owner`, { headers: authHeaders() });
    checkAndRecord(r1, {
      'portfolio_summary: status 200': (r) => r.status === 200,
      'portfolio_summary: has body':   (r) => r.body && r.body.length > 2,
    }, portfolioSummaryTime, 'portfolio_summary');

    shortThink();

    // 2. Trade details for their portfolio
    const r2 = http.get(`${BASE_URL}/v1/trades/details/portfolio/${portfolioId}`, { headers: authHeaders() });
    checkAndRecord(r2, {
      'trade_details: status 200': (r) => r.status === 200,
    }, tradeDetailsTime, 'trade_details');
  });
}

function flowCalendarView(portfolioId) {
  // A user browses the calendar view for today
  group('Flow: Calendar Day View', () => {
    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    const r = http.get(
      `${BASE_URL}/v1/trades/calendar/day?date=${today}&portfolioId=${portfolioId}`,
      { headers: authHeaders() }
    );
    checkAndRecord(r, {
      'calendar_day: status 200': (r) => r.status === 200,
    }, calendarDayTime, 'calendar_day');
  });
}

function flowMonthlySummary(portfolioId) {
  // A user views the monthly trade summary (heavy aggregation)
  group('Flow: Monthly Summary', () => {
    const now = new Date();
    const r = http.get(
      `${BASE_URL}/v1/trade-summary/trades?periodType=MONTH&year=${now.getFullYear()}&month=${now.getMonth() + 1}&portfolioId=${portfolioId}`,
      { headers: authHeaders() }
    );
    checkAndRecord(r, {
      'trade_summary: status 200': (r) => r.status === 200,
    }, tradeSummaryTime, 'trade_summary');
  });
}

function flowFilterTrades(portfolioId) {
  // A user applies filters to find specific trades
  group('Flow: Filter Trades', () => {
    const r = http.get(
      `${BASE_URL}/v1/trades/filter?portfolioIds=${portfolioId}&statuses=WIN&page=0&size=20`,
      { headers: authHeaders() }
    );
    checkAndRecord(r, {
      'filter: status 200': (r) => r.status === 200,
    }, filterTime, 'filter_trades');
  });
}

function flowWriteTrade(portfolioId) {
  // A user saves a new trade (WRITE PATH)
  group('Flow: Write New Trade', () => {
    const now = new Date().toISOString();
    const entryPrice = parseFloat((Math.random() * 4000 + 100).toFixed(2));
    const quantity = Math.floor(Math.random() * 200) + 10;
    const symbols = ['RELIANCE', 'TCS', 'INFY', 'HDFCBANK', 'WIPRO'];
    const symbol = symbols[Math.floor(Math.random() * symbols.length)];

    const trade = {
      portfolioId: portfolioId,
      symbol: symbol,
      tradePositionType: 'LONG',
      status: 'OPEN',
      instrumentInfo: { symbol: symbol, exchange: 'NSE', segment: 'EQ' },
      entryInfo: {
        timestamp: now,
        price: entryPrice,
        quantity: quantity,
        totalValue: parseFloat((entryPrice * quantity).toFixed(2)),
        fees: 50.0,
      },
    };

    const r = http.post(
      `${BASE_URL}/v1/trades/details`,
      JSON.stringify(trade),
      { headers: authHeaders() }
    );

    checkAndRecord(r, {
      'write_trade: status 201': (r) => r.status === 201 || r.status === 200,
    }, writeTradeTime, 'write_trade');
  });
}

// =============================================================
// SECTION 8: MAIN ENTRY POINT
// =============================================================

export default function () {
  const portfolioId = getPortfolioId();

  if (SCENARIO === 'mixed') {
    // 80% read flows, 20% write — production-realistic ratio
    const roll = Math.random();
    if (roll < 0.40) {
      flowDashboardLoad(portfolioId);
    } else if (roll < 0.65) {
      flowMonthlySummary(portfolioId);
    } else if (roll < 0.80) {
      flowFilterTrades(portfolioId);
    } else if (roll < 0.90) {
      flowCalendarView(portfolioId);
    } else {
      flowWriteTrade(portfolioId); // 10% writes
    }
  } else {
    // All other scenarios: full user session simulation
    flowDashboardLoad(portfolioId);
    thinkTime();
    flowMonthlySummary(portfolioId);
    thinkTime();
    flowFilterTrades(portfolioId);
    thinkTime();
    flowCalendarView(portfolioId);
    thinkTime();
  }
}

// =============================================================
// SECTION 9: SETUP & TEARDOWN
// setup() runs ONCE before all VUs start.
// teardown() runs ONCE after all VUs finish.
// =============================================================

export function setup() {
  console.log(`=== SPT Starting ===`);
  console.log(`  Scenario:  ${SCENARIO}`);
  console.log(`  Target:    ${BASE_URL}`);
  console.log(`  Test User: ${TEST_USER}`);
  console.log(`  Auth URL:  ${AUTH_URL}`);

  // Sanity-check: verify the service is up before wasting time on the full test
  const health = http.get(`${BASE_URL}/actuator/health`, { timeout: '10s' });
  if (health.status !== 200) {
    fail(`Service is NOT healthy before test. Status: ${health.status}. Aborting.`);
  }

  // Verify we can authenticate at all
  const authPayload = JSON.stringify({ username: AUTH_USER, password: AUTH_PASS });
  const authRes = http.post(AUTH_URL, authPayload, { headers: { 'Content-Type': 'application/json' } });
  if (authRes.status !== 200) {
    fail(`Auth check failed in setup(). Status: ${authRes.status}. Body: ${authRes.body}`);
  }

  const token = JSON.parse(authRes.body).accessToken;
  console.log(`  Auth OK. Token prefix: ${token.substring(0, 20)}...`);
  console.log(`===================`);

  return { startTime: Date.now() };
}

export function teardown(data) {
  const durationMs = Date.now() - data.startTime;
  const minutes = Math.floor(durationMs / 60000);
  const seconds = Math.floor((durationMs % 60000) / 1000);
  console.log(`=== SPT Complete: ${SCENARIO} ran for ${minutes}m ${seconds}s ===`);
}
