# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-07-24T07:18:01+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, confloat, conint


class Attachment(BaseModel):
    fileName: str | None = None
    fileUrl: str | None = None
    fileType: str | None = None
    uploadedAt: AwareDatetime | None = None
    description: str | None = None


class BrokerType(Enum):
    DHAN = 'DHAN'
    ZERODHA = 'ZERODHA'
    MSTOCK = 'MSTOCK'
    GROW = 'GROW'
    KOTAK = 'KOTAK'
    ANGEL_ONE = 'ANGEL_ONE'
    UPSTOX = 'UPSTOX'
    ICICI = 'ICICI'
    HDFC = 'HDFC'
    MANUAL = 'MANUAL'
    OTHER = 'OTHER'


class TradeType(Enum):
    BUY = 'BUY'
    SELL = 'SELL'


class BasicInfo(BaseModel):
    tradeId: str | None = None
    orderId: str | None = None
    tradeDate: date | None = None
    orderExecutionTime: AwareDatetime | None = None
    brokerType: BrokerType | None = None
    tradeType: TradeType | None = None


class Charges(BaseModel):
    brokerage: float | None = None
    stt: float | None = None
    transactionCharges: float | None = None
    stampDuty: float | None = None
    sebiCharges: float | None = None
    gst: float | None = None
    totalTaxes: float | None = None


class DerivativeInfo(BaseModel):
    expiryDate: date | None = None
    underlyingSymbol: str | None = None
    strikePrice: float | None = None
    isCall: bool | None = None
    isEuropean: bool | None = None
    futureType: str | None = None
    isCashSettled: bool | None = None


class EntryExitInfo(BaseModel):
    timestamp: AwareDatetime | None = None
    price: float | None = None
    quantity: int | None = None
    totalValue: float | None = None
    fees: float | None = None
    reason: str | None = None


class OrderType(Enum):
    MARKET = 'MARKET'
    LIMIT = 'LIMIT'
    STOP = 'STOP'
    STOP_LIMIT = 'STOP_LIMIT'
    STOP_LOSS = 'STOP_LOSS'
    STOP_LOSS_MARKET = 'STOP_LOSS_MARKET'
    TRAILING_STOP = 'TRAILING_STOP'
    FILL_OR_KILL = 'FILL_OR_KILL'
    GOOD_TILL_CANCEL = 'GOOD_TILL_CANCEL'
    GOOD_TILL_DATE = 'GOOD_TILL_DATE'
    AT_THE_OPEN = 'AT_THE_OPEN'
    AT_THE_CLOSE = 'AT_THE_CLOSE'


class ExecutionInfo(BaseModel):
    tradeType: TradeType | None = None
    auction: str | None = None
    quantity: int | None = None
    price: float | None = None
    lotSize: int | None = None
    orderType: OrderType | None = None


class Financials(BaseModel):
    turnover: float | None = None
    netAmount: float | None = None


class InstrumentType(Enum):
    FUTIDX = 'FUTIDX'
    OPTIDX = 'OPTIDX'
    FUTEQ = 'FUTEQ'
    OPTEQ = 'OPTEQ'
    FUTSTK = 'FUTSTK'
    OPTSTK = 'OPTSTK'


class OptionType(Enum):
    CALL = 'CALL'
    PUT = 'PUT'
    NONE = 'NONE'


class FnOInfo(BaseModel):
    instrumentType: InstrumentType | None = None
    expiryDate: date | None = None
    strikePrice: float | None = None
    optionType: OptionType | None = None
    lotSize: float | None = None
    premiumValue: float | None = None


class Exchange(Enum):
    NSE = 'NSE'
    BSE = 'BSE'
    MCX = 'MCX'
    NCDEX = 'NCDEX'
    NYSE = 'NYSE'
    NASDAQ = 'NASDAQ'
    LSE = 'LSE'
    HKEX = 'HKEX'
    TSE = 'TSE'
    SGX = 'SGX'
    EUREX = 'EUREX'
    CME = 'CME'
    OTHER = 'OTHER'


class Segment(Enum):
    EQUITY = 'EQUITY'
    INDEX = 'INDEX'
    EQUITY_FUTURES = 'EQUITY_FUTURES'
    EQUITY_OPTIONS = 'EQUITY_OPTIONS'
    INDEX_FUTURES = 'INDEX_FUTURES'
    INDEX_OPTIONS = 'INDEX_OPTIONS'
    CURRENCY = 'CURRENCY'
    COMMODITY = 'COMMODITY'
    DEBT = 'DEBT'
    MUTUAL_FUND = 'MUTUAL_FUND'
    ETF = 'ETF'
    FUT = 'FUT'
    OPT = 'OPT'
    EQ = 'EQ'
    FO = 'FO'
    INDEX_SEGMENT = 'INDEX_SEGMENT'
    UNKNOWN = 'UNKNOWN'


class Series(Enum):
    EQ = 'EQ'
    BE = 'BE'
    BZ = 'BZ'
    IL = 'IL'
    GC = 'GC'
    CE = 'CE'
    PE = 'PE'
    CA = 'CA'
    PA = 'PA'
    FUT = 'FUT'
    WEEKLY_FUT = 'WEEKLY_FUT'
    MONTHLY_FUT = 'MONTHLY_FUT'
    QUARTERLY_FUT = 'QUARTERLY_FUT'
    UNKNOWN = 'UNKNOWN'


class IndexType(Enum):
    NIFTY = 'NIFTY'
    BANKNIFTY = 'BANKNIFTY'
    MIDCAPNIFTY = 'MIDCAPNIFTY'
    FINNIFTY = 'FINNIFTY'
    NIFTY_NEXT_50 = 'NIFTY_NEXT_50'
    NIFTY_100 = 'NIFTY_100'
    NIFTY_200 = 'NIFTY_200'
    NIFTY_500 = 'NIFTY_500'
    NIFTY_AUTO = 'NIFTY_AUTO'
    NIFTY_FMCG = 'NIFTY_FMCG'
    NIFTY_IT = 'NIFTY_IT'
    NIFTY_METAL = 'NIFTY_METAL'
    NIFTY_PHARMA = 'NIFTY_PHARMA'
    NIFTY_REALTY = 'NIFTY_REALTY'
    SENSEX = 'SENSEX'
    BSE_100 = 'BSE_100'
    BSE_200 = 'BSE_200'
    BSE_500 = 'BSE_500'
    INDIA_VIX = 'INDIA_VIX'
    UNKNOWN = 'UNKNOWN'


class InstrumentInfo(BaseModel):
    symbol: str | None = None
    isin: str | None = None
    rawSymbol: str | None = None
    exchange: Exchange | None = None
    segment: Segment | None = None
    series: Series | None = None
    indexType: IndexType | None = None
    derivativeInfo: DerivativeInfo | None = None
    description: str | None = None
    currency: str | None = None
    lotSize: str | None = None
    index: bool | None = None
    derivative: bool | None = None
    formattedDescription: str | None = None
    baseSymbol: str | None = None


class Status(Enum):
    WIN = 'WIN'
    LOSS = 'LOSS'
    OPEN = 'OPEN'
    BREAK_EVEN = 'BREAK_EVEN'


class TradePositionType(Enum):
    LONG = 'LONG'
    SHORT = 'SHORT'


class TradeEntryExistReasoning(BaseModel):
    technicalReasons: list[dict[str, str]] | None = None
    fundamentalReasons: list[dict[str, str]] | None = None
    primaryReason: str | None = None
    reasoningSummary: str | None = None
    confidenceLevel: int | None = None
    supportingIndicators: list[str] | None = None
    conflictingIndicators: list[str] | None = None
    exitPrimaryReason: str | None = None
    exitReasoningSummary: str | None = None
    exitConfidenceLevel: int | None = None
    exitSupportingIndicators: list[str] | None = None
    exitConflictingIndicators: list[str] | None = None
    exitQualityScore: int | None = None
    streategy: str | None = None


class TradeMetrics(BaseModel):
    profitLoss: float | None = None
    profitLossPercentage: float | None = None
    returnOnEquity: float | None = None
    riskAmount: float | None = None
    rewardAmount: float | None = None
    riskRewardRatio: float | None = None
    holdingTimeDays: int | None = None
    holdingTimeHours: int | None = None
    holdingTimeMinutes: int | None = None
    maxAdverseExcursion: float | None = None
    maxFavorableExcursion: float | None = None


class TradeModel(BaseModel):
    basicInfo: BasicInfo | None = None
    instrumentInfo: InstrumentInfo | None = None
    executionInfo: ExecutionInfo | None = None
    fnoInfo: FnOInfo | None = None
    charges: Charges | None = None
    financials: Financials | None = None


class TradePsychologyData(BaseModel):
    categorizedTags: dict[str, list[str]] | None = None
    psychologyNotes: str | None = None
    entryPsychologyFactors: list[dict[str, str]] | None = None
    exitPsychologyFactors: list[dict[str, str]] | None = None
    behaviorPatterns: list[dict[str, str]] | None = None


class ErrorResponse(BaseModel):
    status: str | None = Field(
        None, description='HTTP status description', examples=['BAD_REQUEST']
    )
    code: int | None = Field(None, description='HTTP status code', examples=[400])
    message: str | None = Field(
        None,
        description='Primary error message',
        examples=['Invalid input provided for trade details.'],
    )
    timestamp: AwareDatetime | None = Field(
        None, description='The timestamp when the error occurred.'
    )
    details: list[str] | None = Field(
        None, description='Additional error details or validation messages.'
    )
    path: str | None = Field(
        None,
        description='The API path that generated the error.',
        examples=['/v1/trades/details'],
    )


class NotebookTagRequest(BaseModel):
    name: str = Field(..., description='Name of the tag', examples=['Psychology'])
    color: str | None = Field(
        None, description='Hex color code for UI display', examples=['#FF5733']
    )
    description: str | None = Field(
        None,
        description='Optional description of what the tag represents',
        examples=['Tags related to trading psychology and emotions'],
    )


class NotebookTagResponse(BaseModel):
    id: str | None = Field(
        None, description='Unique identifier of the tag', examples=['tag-987']
    )
    userId: str | None = Field(
        None, description='ID of the user who owns the tag', examples=['usr-1234']
    )
    name: str | None = Field(
        None, description='Name of the tag', examples=['Psychology']
    )
    color: str | None = Field(
        None, description='Hex color code for UI display', examples=['#FF5733']
    )
    description: str | None = Field(
        None,
        description='Description of the tag',
        examples=['Tags related to trading psychology and emotions'],
    )
    createdAt: AwareDatetime | None = Field(
        None, description='Timestamp when the tag was created'
    )
    updatedAt: AwareDatetime | None = Field(
        None, description='Timestamp when the tag was last updated'
    )


class NotebookGoalDetails(BaseModel):
    targetDate: AwareDatetime | None = Field(
        None,
        description='The target date to achieve this goal',
        examples=['2024-12-31T23:59:59Z'],
    )
    targetValue: float | None = Field(
        None,
        description='The mathematical target value to hit (e.g. 50000 for a profit goal)',
        examples=[50000.0],
    )
    currentValue: float | None = Field(
        None, description='The current value towards the goal', examples=[12500.5]
    )
    currency: str | None = Field(
        None,
        description='Currency of the goal if applicable (ISO 4217 code)',
        examples=['USD'],
    )
    status: str | None = Field(
        None,
        description='Status of the goal (e.g., IN_PROGRESS, ACHIEVED, FAILED)',
        examples=['IN_PROGRESS'],
    )


class Type(Enum):
    FOLDER = 'FOLDER'
    NOTE = 'NOTE'
    GOAL = 'GOAL'


class NotebookItemRequest(BaseModel):
    type: Type
    parentId: str | None = Field(
        None, description='ID of the parent folder, if any', examples=['nb-folder-123']
    )
    title: str = Field(
        ..., description='Title of the notebook item', examples=['Q3 Trading Goals']
    )
    content: str | None = Field(
        None,
        description='Content or body of the item, usually Markdown or HTML',
        examples=['Focusing on preserving capital this quarter.'],
    )
    tagIds: list[str] | None = None
    metadata: dict[str, dict[str, Any]] | None = Field(
        None, description='Arbitrary metadata for the item'
    )
    goalDetails: NotebookGoalDetails | None = None


class NotebookItemResponse(BaseModel):
    id: str | None = Field(
        None,
        description='Unique identifier of the notebook item',
        examples=['nb-item-999'],
    )
    userId: str | None = Field(
        None, description='ID of the user who owns the item', examples=['usr-1234']
    )
    type: Type | None = None
    parentId: str | None = Field(
        None, description='ID of the parent folder, if any', examples=['nb-folder-123']
    )
    title: str | None = Field(
        None, description='Title of the notebook item', examples=['Q3 Trading Goals']
    )
    content: str | None = Field(
        None,
        description='Content or body of the item',
        examples=['Focusing on preserving capital this quarter.'],
    )
    tagIds: list[str] | None = None
    metadata: dict[str, dict[str, Any]] | None = Field(
        None, description='Flexible key-value metadata for extensible attributes'
    )
    goalDetails: NotebookGoalDetails | None = None
    createdAt: AwareDatetime | None = Field(
        None, description='Timestamp when the item was created'
    )
    updatedAt: AwareDatetime | None = Field(
        None, description='Timestamp when the item was last updated'
    )


class BehaviorPatternSummary(BaseModel):
    summary: str | None = Field(
        None,
        description="Brief summary of the day's trading activities and observations",
        examples=[
            'Active trading day with 3 positions. Strong bullish momentum in IT sector.'
        ],
    )
    mood: str | None = Field(
        None,
        description='Overall mood for the day (e.g., CONFIDENT, ANXIOUS, NEUTRAL, OPTIMISTIC, CAUTIOUS)',
        examples=['CONFIDENT'],
    )
    marketSentiment: conint(ge=1, le=10) | None = Field(
        None,
        description='Market sentiment for the day (1-10: 1=bearish, 10=bullish)',
        examples=[7],
    )
    tags: list[str] | None = Field(
        None,
        description="Tags categorizing the day's activities or themes",
        examples=[['high-volatility', 'options-trading', 'profit-day']],
    )


class TradeJournalEntryRequest(BaseModel):
    tradeId: str | None = Field(
        None,
        description='Optional ID of the trade associated with this entry',
        examples=['TRD-491293'],
    )
    title: str = Field(
        ..., description='Title of the journal entry', examples=['E-mini S&P Breakout']
    )
    content: str = Field(
        ...,
        description='Detailed content or notes for the journal entry',
        examples=[
            'Saw strong buying pressure at the open, entered on the 5-min pullback.'
        ],
    )
    customFields: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Custom key-value fields for flexible data storage',
        examples=[{'marketCondition': 'Trending'}],
    )
    entryDate: AwareDatetime = Field(
        ..., description='The date and time this entry occurred'
    )
    imageUrls: list[str] | None = Field(
        None,
        deprecated=True,
        description='Legacy field for image URLs. Use attachments instead.',
    )
    attachments: list[Attachment] | None = Field(
        None, description='List of structured attachments (images, PDFs, etc.)'
    )
    chartUrls: list[str] | None = Field(
        None,
        description='URLs to charting platform screenshots',
        examples=[['https://cdn.example.com/charts/es1.png']],
    )
    documentUrls: list[str] | None = Field(
        None, description='URLs to related documents'
    )
    videoUrls: list[str] | None = Field(
        None, description='URLs to video analysis recordings'
    )
    externalUrls: list[str] | None = Field(
        None, description='URLs to external resources (news, research)'
    )
    relatedTradeIds: list[str] | None = Field(
        None,
        description='List of related trade IDs if this entry spans multiple trades',
    )
    tagIds: list[str] | None = Field(
        None, description='List of Notebook Tag IDs to categorize this entry'
    )
    behaviorPatternSummaries: list[BehaviorPatternSummary] | None = Field(
        None, description='Daily behavior pattern summaries associated with this entry'
    )


class TradeJournalEntryResponse(BaseModel):
    id: str | None = Field(
        None,
        description='Unique identifier for the journal entry',
        examples=['JNL-12345'],
    )
    userId: str | None = Field(
        None,
        description='User ID who created the journal entry',
        examples=['usr_98765'],
    )
    tradeId: str | None = Field(
        None, description='Associated trade ID (optional)', examples=['TRD-491293']
    )
    title: str | None = Field(
        None, description='Journal entry title', examples=['E-mini S&P Breakout']
    )
    content: str | None = Field(
        None,
        description='Journal entry content/body',
        examples=[
            'Saw strong buying pressure at the open, entered on the 5-min pullback.'
        ],
    )
    customFields: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Custom fields for extensibility',
        examples=[{'marketCondition': 'Trending'}],
    )
    entryDate: AwareDatetime | None = Field(
        None, description='Date of the journal entry'
    )
    imageUrls: list[str] | None = Field(
        None,
        deprecated=True,
        description='Legacy image URLs (deprecated - use attachments instead)',
    )
    attachments: list[Attachment] | None = Field(
        None,
        description='List of attachments with metadata (fileName, fileUrl, fileType, uploadedAt, description)',
    )
    chartUrls: list[str] | None = Field(
        None,
        description='URLs to chart analysis images',
        examples=[['https://cdn.example.com/charts/es1.png']],
    )
    documentUrls: list[str] | None = Field(
        None, description='URLs to PDF documents, notes, etc.'
    )
    videoUrls: list[str] | None = Field(
        None, description='URLs to video analysis or recordings'
    )
    externalUrls: list[str] | None = Field(
        None, description='External reference URLs (news articles, etc.)'
    )
    relatedTradeIds: list[str] | None = Field(None, description='IDs of related trades')
    tagIds: list[str] | None = Field(
        None, description='Notebook Tag IDs associated with this entry'
    )
    behaviorPatternSummaries: list[BehaviorPatternSummary] | None = Field(
        None, description='List of daily behavior pattern summaries'
    )
    createdAt: AwareDatetime | None = Field(
        None, description='Timestamp when the entry was created'
    )
    updatedAt: AwareDatetime | None = Field(
        None, description='Timestamp when the entry was last updated'
    )


class Category(Enum):
    DAILY_CHECKIN = 'DAILY_CHECKIN'
    PRE_MARKET = 'PRE_MARKET'
    POST_MARKET = 'POST_MARKET'
    TRADE_RECAP = 'TRADE_RECAP'
    WEEKLY_REVIEW = 'WEEKLY_REVIEW'
    MONTHLY_REVIEW = 'MONTHLY_REVIEW'
    QUARTERLY_REVIEW = 'QUARTERLY_REVIEW'
    CUSTOM = 'CUSTOM'


class FieldType(Enum):
    TEXT = 'TEXT'
    TEXTAREA = 'TEXTAREA'
    CHECKBOX = 'CHECKBOX'
    CHECKBOX_LIST = 'CHECKBOX_LIST'
    DROPDOWN = 'DROPDOWN'
    DATE = 'DATE'
    TIME = 'TIME'
    NUMBER = 'NUMBER'
    IMAGE_UPLOAD = 'IMAGE_UPLOAD'


class TemplateFieldRequest(BaseModel):
    fieldId: str = Field(
        ...,
        description='Internal unique identifier for this field within the template',
        examples=['field_market_trend'],
    )
    fieldLabel: str = Field(
        ...,
        description='Display label for the field in the UI',
        examples=['Market Trend'],
    )
    fieldType: FieldType
    placeholder: str | None = Field(
        None,
        description='Placeholder text to show in the input',
        examples=['Select market trend...'],
    )
    defaultValue: str | None = Field(
        None, description='Default value to pre-fill', examples=['BULLISH']
    )
    required: bool | None = Field(
        None, description='Indicates whether this field is mandatory', examples=[True]
    )
    order: conint(ge=0) | None = Field(
        None, description='Display order of the field in the template UI', examples=[1]
    )
    options: list[str] | None = Field(
        None,
        description='List of options if the fieldType is a selection type (like DROPDOWN or RADIO)',
        examples=[['BULLISH', 'BEARISH', 'CHOPPY']],
    )
    minLength: conint(ge=0) | None = Field(
        None, description='Minimum length or value', examples=[1]
    )
    maxLength: conint(ge=1) | None = Field(
        None, description='Maximum length or value', examples=[100]
    )
    validationPattern: str | None = Field(
        None,
        description='Regex pattern for validating text fields',
        examples=['^[a-zA-Z0-9]*$'],
    )
    helpText: str | None = Field(
        None,
        description='Helper text or tooltip to guide the user',
        examples=[
            'Indicate the overall trend of the broader market during this trade.'
        ],
    )


class TemplateFieldResponse(BaseModel):
    fieldId: str | None = Field(
        None,
        description='Internal unique identifier for this field within the template',
        examples=['field_market_trend'],
    )
    fieldLabel: str | None = Field(
        None,
        description='Display label for the field in the UI',
        examples=['Market Trend'],
    )
    fieldType: FieldType | None = None
    placeholder: str | None = Field(
        None,
        description='Placeholder text to show in the input',
        examples=['Select market trend...'],
    )
    defaultValue: str | None = Field(
        None, description='Default value to pre-fill', examples=['BULLISH']
    )
    required: bool | None = Field(
        None, description='Indicates whether this field is mandatory', examples=[True]
    )
    order: int | None = Field(
        None, description='Display order of the field in the template UI', examples=[1]
    )
    options: list[str] | None = Field(
        None,
        description='List of options if the fieldType is a selection type (like DROPDOWN or RADIO)',
        examples=[['BULLISH', 'BEARISH', 'CHOPPY']],
    )
    minLength: int | None = Field(
        None, description='Minimum length or value', examples=[1]
    )
    maxLength: int | None = Field(
        None, description='Maximum length or value', examples=[100]
    )
    validationPattern: str | None = Field(
        None,
        description='Regex pattern for validating text fields',
        examples=['^[a-zA-Z0-9]*$'],
    )
    helpText: str | None = Field(
        None,
        description='Helper text or tooltip to guide the user',
        examples=[
            'Indicate the overall trend of the broader market during this trade.'
        ],
    )


class MetricsFilterConfig(BaseModel):
    portfolioIds: list[str] | None = Field(
        None,
        description='List of portfolio IDs to filter by',
        examples=[['port-123', 'port-456']],
    )
    dateRange: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Date range filter configuration.',
        examples=[{'startDate': '2023-01-01', 'endDate': '2023-12-31'}],
    )
    timePeriod: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Time period filter configuration.',
        examples=[{'type': 'QUARTER', 'value': 'Q3', 'year': 2023}],
    )
    metricTypes: list[str] | None = Field(
        None,
        description='List of metric types to include in the response',
        examples=[['PROFIT_LOSS', 'WIN_RATE', 'RISK_REWARD']],
    )
    groupBy: list[str] | None = Field(
        None,
        description='Fields to group the metrics by',
        examples=[['INSTRUMENT', 'STRATEGY']],
    )
    instruments: list[str] | None = Field(
        None,
        description='List of specific instrument symbols to filter by',
        examples=[['AAPL', 'TSLA', 'BTC-USD']],
    )
    instrumentFilters: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Additional filters specific to instruments, such as asset class or sector.',
        examples=[{'assetClass': 'EQUITY', 'sector': 'TECHNOLOGY'}],
    )
    tradeCharacteristics: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Filters based on trade characteristics (e.g., long/short, leverage used).',
        examples=[{'direction': 'LONG', 'minLeverage': 1.5}],
    )
    profitLossFilters: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Filters based on profit and loss metrics.',
        examples=[{'minProfit': 100.0, 'maxLoss': -50.0}],
    )


class FavoriteFilterResponse(BaseModel):
    id: str | None = Field(
        None,
        description='Unique identifier of the favorite filter',
        examples=['507f1f77bcf86cd799439011'],
    )
    name: str | None = Field(
        None,
        description='User-defined name for the filter',
        examples=['Q3 High Volatility Trades'],
    )
    description: str | None = Field(
        None,
        description='Optional description of what the filter captures',
        examples=['Trades in technology sector with high leverage'],
    )
    createdAt: AwareDatetime | None = Field(
        None, description='Creation timestamp', examples=['2023-11-15T10:30:00Z']
    )
    updatedAt: AwareDatetime | None = Field(
        None, description='Last update timestamp', examples=['2023-11-15T14:45:00Z']
    )
    filterConfig: MetricsFilterConfig | None = None
    default: bool | None = None


class FilterTradeDetailsRequest(BaseModel):
    favoriteFilterId: str | None = Field(
        None,
        description='Favorite filter ID to apply (optional - if provided, merges with this request)',
        examples=['fav-filter-77a8b9'],
    )
    metricsConfig: MetricsFilterConfig


class Pageable(BaseModel):
    page: conint(ge=0) | None = None
    size: conint(ge=1) | None = None
    sort: list[str] | None = None


class FilterSummary(BaseModel):
    portfolioIds: list[str] | None = None
    symbols: list[str] | None = None
    statuses: list[str] | None = None
    dateRange: str | None = None
    strategies: list[str] | None = None
    profitLossRange: str | None = None
    holdingTimeRange: str | None = None


class AssetClass(BaseModel):
    code: str | None = None
    description: str | None = None


class PerformanceMetrics(BaseModel):
    totalProfitLoss: float | None = None
    totalProfitLossPercentage: float | None = None
    winRate: float | None = None
    profitFactor: float | None = None
    expectancy: float | None = None
    annualizedReturn: float | None = None
    monthlyReturn: float | None = None
    quarterlyReturn: float | None = None
    yearToDateReturn: float | None = None
    averageWinningTrade: float | None = None
    averageLosingTrade: float | None = None
    largestWinningTrade: float | None = None
    largestLosingTrade: float | None = None
    winLossRatio: float | None = None
    returnStandardDeviation: float | None = None
    profitConsistency: float | None = None
    maxDrawdown: float | None = None
    longestWinningStreak: int | None = None
    longestLosingStreak: int | None = None
    currentStreak: int | None = None
    averageHoldingTimeWinning: float | None = None
    averageHoldingTimeLosing: float | None = None
    averageHoldingTimeOverall: float | None = None
    returnOnCapital: float | None = None
    returnPerUnit: float | None = None
    tradesPerDay: float | None = None
    tradesPerWeek: float | None = None
    tradesPerMonth: float | None = None
    tradingDays: int | None = None
    averageVolumePerTrade: float | None = None
    lastWinningTradeDate: AwareDatetime | None = None
    lastLosingTradeDate: AwareDatetime | None = None
    bestDayDate: AwareDatetime | None = None
    worstDayDate: AwareDatetime | None = None
    bestDayProfit: float | None = None
    worstDayLoss: float | None = None


class PortfolioMetrics(BaseModel):
    totalTrades: int | None = Field(
        None, description='Total number of trades taken', examples=[150]
    )
    winningTrades: int | None = Field(
        None, description='Number of winning trades', examples=[80]
    )
    losingTrades: int | None = Field(
        None, description='Number of losing trades', examples=[60]
    )
    breakEvenTrades: int | None = Field(
        None, description='Number of breakeven trades', examples=[10]
    )
    openPositions: int | None = Field(
        None, description='Current open positions', examples=[3]
    )
    winRate: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='Win rate percentage', examples=[53.33]
    )
    lossRate: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='Loss rate percentage', examples=[40.0]
    )
    profitFactor: float | None = Field(
        None, description='Ratio of gross profit to gross loss', examples=[1.85]
    )
    expectancy: float | None = Field(
        None, description='Average expected profit per trade', examples=[125.5]
    )
    totalValue: float | None = Field(
        None, description='Total portfolio value', examples=[65400.25]
    )
    totalProfit: float | None = Field(
        None, description='Total gross profit', examples=[25000.0]
    )
    totalLoss: float | None = Field(
        None, description='Total gross loss', examples=[9599.75]
    )
    netProfitLoss: float | None = Field(
        None, description='Net PnL', examples=[15400.25]
    )
    netProfitLossPercentage: confloat(ge=-100.0) | None = Field(
        None, description='Net PnL percentage', examples=[30.8]
    )
    maxDrawdown: float | None = Field(
        None, description='Maximum drawdown value', examples=[4500.0]
    )
    maxDrawdownPercentage: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='Maximum drawdown percentage', examples=[8.5]
    )
    sharpeRatio: float | None = Field(None, description='Sharpe ratio', examples=[1.25])
    sortinoRatio: float | None = Field(
        None, description='Sortino ratio', examples=[1.5]
    )
    monthlyReturns: dict[str, float] | None = Field(
        None,
        description='Monthly returns mapped by month (YYYY-MM)',
        examples=[{'2023-01': 5.5, '2023-02': -1.2}],
    )
    weeklyReturns: dict[str, float] | None = Field(
        None,
        description='Weekly returns mapped by ISO week (YYYY-Www)',
        examples=[{'2023-W01': 1.2, '2023-W02': 0.8}],
    )


class RiskMetrics(BaseModel):
    maxDrawdown: float | None = None
    maxDrawdownPercentage: float | None = None
    averageDrawdown: float | None = None
    currentDrawdown: float | None = None
    recoveryTime: int | None = None
    standardDeviation: float | None = None
    downside: float | None = None
    upside: float | None = None
    sharpeRatio: float | None = None
    sortinoRatio: float | None = None
    calmarRatio: float | None = None
    sterlingRatio: float | None = None
    averageRiskPerTrade: float | None = None
    riskRewardRatio: float | None = None
    valueAtRisk: float | None = None
    averagePositionSize: float | None = None
    largestPositionSize: float | None = None
    positionSizeVariance: float | None = None
    marketCorrelation: float | None = None
    sectorCorrelation: float | None = None
    probabilityOfRuin: float | None = None
    consecutiveLossesToRuin: int | None = None
    topHoldingPercentage: float | None = None
    topFiveConcentration: float | None = None


class StrategyPerformanceMetrics(BaseModel):
    strategyName: str | None = None
    strategyDescription: str | None = None
    strategyTags: list[str] | None = None
    strategyInceptionDate: AwareDatetime | None = None
    totalProfitLoss: float | None = None
    winRate: float | None = None
    profitFactor: float | None = None
    expectancy: float | None = None
    sharpeRatio: float | None = None
    consistencyScore: float | None = None
    performanceStability: float | None = None
    strategyDrawdownPeriods: list[AwareDatetime] | None = None
    strategyOutperformancePeriods: list[AwareDatetime] | None = None
    performanceByMarketType: dict[str, float] | None = None
    performanceByVolatility: dict[str, float] | None = None
    marketNeutralScore: float | None = None
    adaptabilityScore: float | None = None
    lastStrategyAdjustment: AwareDatetime | None = None
    strategyEvolutionNotes: list[str] | None = None
    benchmarkOutperformance: float | None = None
    peerGroupRanking: float | None = None
    correlationWithOtherStrategies: dict[str, float] | None = None
    maxDrawdown: float | None = None
    recoveryFactor: float | None = None
    ulcerIndex: float | None = None
    painIndex: float | None = None
    parameterSensitivity: dict[str, float] | None = None
    optimizationSuggestions: list[str] | None = None
    optimizationPotential: float | None = None
    executionQuality: float | None = None
    planAdherenceScore: float | None = None
    signalResponseTime: float | None = None


class TradeDistributionMetrics(BaseModel):
    tradesByDay: dict[str, int] | None = None
    tradesByHour: dict[str, int] | None = None
    tradesByMonth: dict[str, int] | None = None
    tradesByQuarter: dict[str, int] | None = None
    profitByDay: dict[str, float] | None = None
    profitByHour: dict[str, float] | None = None
    profitByMonth: dict[str, float] | None = None
    profitByQuarter: dict[str, float] | None = None
    tradeCountByAssetClass: dict[str, int] | None = None
    profitByAssetClass: dict[str, float] | None = None
    winRateByAssetClass: dict[str, float] | None = None
    tradeCountBySector: dict[str, int] | None = None
    profitBySector: dict[str, float] | None = None
    winRateBySector: dict[str, float] | None = None
    tradeCountByStrategy: dict[str, int] | None = None
    profitByStrategy: dict[str, float] | None = None
    winRateByStrategy: dict[str, float] | None = None
    tradesByDuration: dict[str, int] | None = None
    profitByDuration: dict[str, float] | None = None
    winRateByDuration: dict[str, float] | None = None
    tradesByPositionSize: dict[str, int] | None = None
    profitByPositionSize: dict[str, float] | None = None
    winRateByPositionSize: dict[str, float] | None = None
    tradesByMarketCondition: dict[str, int] | None = None
    profitByMarketCondition: dict[str, float] | None = None
    winRateByMarketCondition: dict[str, float] | None = None
    tradesBySetup: dict[str, int] | None = None
    profitBySetup: dict[str, float] | None = None
    winRateBySetup: dict[str, float] | None = None


class TradePatternMetrics(BaseModel):
    overallWinRate: float | None = None
    overallExpectancy: float | None = None
    overallRiskRewardRatio: float | None = None
    patternFrequency: dict[str, int] | None = None
    patternProfitLoss: dict[str, float] | None = None
    patternWinRate: dict[str, float] | None = None
    patternExpectancy: dict[str, float] | None = None
    patternRiskRewardRatio: dict[str, float] | None = None
    mostProfitablePatterns: list[dict[str, str]] | None = None
    leastProfitablePatterns: list[dict[str, str]] | None = None
    entryPsychologyFrequency: dict[str, int] | None = None
    entryPsychologyProfitLoss: dict[str, float] | None = None
    entryPsychologyWinRate: dict[str, float] | None = None
    mostProfitableEntryPsychology: list[dict[str, str]] | None = None
    leastProfitableEntryPsychology: list[dict[str, str]] | None = None
    entryPsychologyExpectancy: dict[str, float] | None = None
    entryPsychologyRiskRewardRatio: dict[str, float] | None = None
    exitPsychologyFrequency: dict[str, int] | None = None
    exitPsychologyProfitLoss: dict[str, float] | None = None
    exitPsychologyWinRate: dict[str, float] | None = None
    mostProfitableExitPsychology: list[dict[str, str]] | None = None
    leastProfitableExitPsychology: list[dict[str, str]] | None = None
    exitPsychologyExpectancy: dict[str, float] | None = None
    exitPsychologyRiskRewardRatio: dict[str, float] | None = None
    emotionalControlScore: float | None = None
    planAdherenceScore: float | None = None
    impulsiveTradePercentage: float | None = None
    fearBasedExitPercentage: float | None = None
    greedBasedEntryPercentage: float | None = None
    disciplineScore: float | None = None
    impulsivityScore: float | None = None
    patternConsistencyScore: float | None = None
    patternExecutionQuality: dict[str, float] | None = None
    patternDeviationRate: float | None = None
    psychologyImprovementTrend: float | None = None
    psychologyByTimeframe: dict[str, float] | None = None
    emotionalResilience: float | None = None
    patternPsychologyCorrelation: dict[str, float] | None = None
    psychologyRecommendations: list[str] | None = None
    patternOptimizationSuggestions: list[str] | None = None
    averageScaleInQuality: float | None = None
    averageScaleOutQuality: float | None = None
    stopLossAdherenceRate: float | None = None
    targetAdherenceRate: float | None = None
    adjustmentEffectivenessScore: float | None = None
    entryDecisionQuality: float | None = None
    exitDecisionQuality: float | None = None
    overallDecisionQuality: float | None = None
    decisionConsistency: float | None = None
    adaptabilityScore: float | None = None
    overconfidenceIndex: float | None = None


class TradeTimingMetrics(BaseModel):
    averageEntryEfficiency: float | None = None
    entryTimingScore: float | None = None
    earlyEntries: dict[str, int] | None = None
    lateEntries: dict[str, int] | None = None
    optimalEntries: dict[str, int] | None = None
    averageExitEfficiency: float | None = None
    exitTimingScore: float | None = None
    earlyExits: dict[str, int] | None = None
    lateExits: dict[str, int] | None = None
    optimalExits: dict[str, int] | None = None
    marketDirectionAccuracy: float | None = None
    trendAlignmentPercentage: float | None = None
    counterTrendSuccessRate: float | None = None
    seasonalPerformance: dict[str, float] | None = None
    monthlyPerformance: dict[str, float] | None = None
    dayOfWeekPerformance: dict[str, float] | None = None
    timeOfDayPerformance: dict[str, float] | None = None
    highVolatilityWinRate: float | None = None
    lowVolatilityWinRate: float | None = None
    volatilityAdaptationScore: float | None = None
    preEventPerformance: float | None = None
    postEventPerformance: float | None = None
    newsReactionScore: float | None = None
    timingImprovementTrend: float | None = None
    lastTimingAssessment: AwareDatetime | None = None
    timingByStrategy: dict[str, float] | None = None


class TradingFeedback(BaseModel):
    strengthAreas: list[str] | None = None
    improvementAreas: list[str] | None = None
    psychologyInsights: dict[str, list[str]] | None = None
    emotionalPatternObservations: list[str] | None = None
    recommendedBehaviorChanges: list[str] | None = None
    tradingHabitsToReinforce: list[str] | None = None
    patternSpecificFeedback: dict[str, str] | None = None
    successPatternRecommendations: list[str] | None = None
    entryDecisionFeedback: str | None = None
    exitDecisionFeedback: str | None = None
    overallDecisionQualityFeedback: str | None = None
    riskManagementFeedback: str | None = None
    riskManagementSuggestions: list[str] | None = None


class Widget(BaseModel):
    id: str | None = Field(
        None, description='Unique identifier of the widget', examples=['WIDGET-01']
    )
    type: str | None = Field(
        None,
        description='Type of the widget (e.g., CHART, TABLE, METRIC)',
        examples=['CHART'],
    )
    row: int | None = Field(None, description='Grid row position', examples=[1])
    col: int | None = Field(None, description='Grid column position', examples=[1])
    sizeX: int | None = Field(
        None, description='Width of the widget in grid units', examples=[2]
    )
    sizeY: int | None = Field(
        None, description='Height of the widget in grid units', examples=[2]
    )
    config: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Widget-specific configuration parameters',
        examples=[{'chartType': 'BAR', 'colorScheme': 'DARK'}],
    )


class WidgetLayout(BaseModel):
    widgets: list[Widget] | None = Field(None, description='List of configured widgets')


class DashboardPreferencesResponse(BaseModel):
    id: str | None = Field(
        None,
        description='Unique identifier of the preferences record',
        examples=['PREF-998123'],
    )
    userId: str | None = Field(
        None, description='User ID these preferences belong to', examples=['USR-55443']
    )
    defaultMetricTypes: list[str] | None = Field(
        None,
        description='Default metric types to display on the dashboard',
        examples=[['PROFIT_LOSS', 'WIN_RATE', 'RISK_REWARD']],
    )
    favoritePortfolioIds: list[str] | None = Field(
        None,
        description='List of favorite portfolio IDs to show by default',
        examples=[['PF-100', 'PF-200']],
    )
    defaultTimeRange: str | None = Field(
        None, description='Default time range selection', examples=['LAST_30_DAYS']
    )
    customDaysRange: int | None = Field(
        None,
        description='Custom days range if defaultTimeRange is CUSTOM',
        examples=[45],
    )
    showProfitLossChart: bool | None = Field(
        None,
        description='Toggle to show or hide the Profit/Loss chart',
        examples=[True],
    )
    showWinRateChart: bool | None = Field(
        None, description='Toggle to show or hide the Win Rate chart', examples=[True]
    )
    showTradeFrequencyChart: bool | None = Field(
        None,
        description='Toggle to show or hide the Trade Frequency chart',
        examples=[False],
    )
    showInstrumentDistributionChart: bool | None = Field(
        None,
        description='Toggle to show or hide the Instrument Distribution chart',
        examples=[True],
    )
    widgetLayout: WidgetLayout | None = None
    additionalCharts: dict[str, bool] | None = Field(
        None,
        description='Map of additional custom charts and their visibility status',
        examples=[{'drawdownChart': True, 'heatMap': False}],
    )
    createdAt: AwareDatetime | None = Field(None, description='Creation timestamp')
    updatedAt: AwareDatetime | None = Field(None, description='Last update timestamp')


class DateRangeFilter(BaseModel):
    startDate: date = Field(
        ..., description='Start date for the metrics calculation period'
    )
    endDate: date = Field(
        ..., description='End date for the metrics calculation period'
    )


class InstrumentFilterCriteria(BaseModel):
    marketSegments: list[str] | None = Field(
        None,
        description='Filter trades by market segment (EQUITY, INDEX, EQUITY_FUTURES, INDEX_FUTURES, EQUITY_OPTIONS, INDEX_OPTIONS)',
    )
    baseSymbols: list[str] | None = Field(
        None,
        description='Filter trades by specific base symbols (e.g., NIFTY, BANKNIFTY, RELIANCE)',
    )
    indexTypes: list[str] | None = Field(
        None,
        description='Filter trades by index type (e.g., NIFTY, BANKNIFTY, FINNIFTY)',
    )
    derivativeTypes: list[str] | None = Field(
        None, description='Filter trades by derivative type (FUTURES, OPTIONS)'
    )


class TimePeriod(Enum):
    TODAY = 'TODAY'
    YESTERDAY = 'YESTERDAY'
    LAST_7_DAYS = 'LAST_7_DAYS'
    LAST_14_DAYS = 'LAST_14_DAYS'
    LAST_30_DAYS = 'LAST_30_DAYS'
    THIS_WEEK = 'THIS_WEEK'
    LAST_WEEK = 'LAST_WEEK'
    THIS_MONTH = 'THIS_MONTH'
    LAST_MONTH = 'LAST_MONTH'
    THIS_QUARTER = 'THIS_QUARTER'
    LAST_QUARTER = 'LAST_QUARTER'
    THIS_YEAR = 'THIS_YEAR'
    LAST_YEAR = 'LAST_YEAR'
    LAST_3_MONTHS = 'LAST_3_MONTHS'
    LAST_6_MONTHS = 'LAST_6_MONTHS'
    LAST_12_MONTHS = 'LAST_12_MONTHS'
    LAST_2_YEARS = 'LAST_2_YEARS'
    LAST_3_YEARS = 'LAST_3_YEARS'
    LAST_5_YEARS = 'LAST_5_YEARS'
    CUSTOM = 'CUSTOM'


class ProfitLossFilter(BaseModel):
    minProfitLoss: float | None = Field(
        None, description='Filter trades by minimum profit/loss amount'
    )
    maxProfitLoss: float | None = Field(
        None, description='Filter trades by maximum profit/loss amount'
    )
    minPositionSize: float | None = Field(
        None, description='Filter trades by minimum position size'
    )
    maxPositionSize: float | None = Field(
        None, description='Filter trades by maximum position size'
    )


class TradeCharacteristicsFilter(BaseModel):
    strategies: list[str] | None = Field(
        None, description='Filter trades by specific strategies'
    )
    tags: list[str] | None = Field(None, description='Filter trades by specific tags')
    directions: list[str] | None = Field(
        None, description='Filter trades by trade direction (LONG, SHORT)'
    )
    statuses: list[str] | None = Field(
        None, description='Filter trades by specific trade statuses (OPEN, CLOSED)'
    )
    minHoldingTimeHours: int | None = Field(
        None, description='Filter trades by minimum holding time in hours'
    )
    maxHoldingTimeHours: int | None = Field(
        None, description='Filter trades by maximum holding time in hours'
    )


class UseTemplateRequest(BaseModel):
    templateId: str
    fieldValues: dict[str, dict[str, Any]] | None = None
    tradeId: str | None = None
    customTitle: str | None = None


class Granularity(Enum):
    YEARLY = 'YEARLY'
    MONTHLY = 'MONTHLY'
    DAILY = 'DAILY'


class HeatmapRequest(BaseModel):
    portfolioIds: list[str] | None = None
    granularity: Granularity | None = None
    financialYear: int | None = None
    month: int | None = None
    includeTradeDetails: bool | None = None


class PeriodProfitLossData(BaseModel):
    periodId: str | None = None
    profitLoss: float | None = None
    winCount: int | None = None
    lossCount: int | None = None
    winRate: float | None = None
    avgWinAmount: float | None = None
    avgLossAmount: float | None = None
    maxWinAmount: float | None = None
    maxLossAmount: float | None = None


class GranularityType(Enum):
    YEARLY = 'YEARLY'
    MONTHLY = 'MONTHLY'
    DAILY = 'DAILY'


class ComparisonType(Enum):
    TIME_PERIOD = 'TIME_PERIOD'
    PORTFOLIO = 'PORTFOLIO'
    STRATEGY = 'STRATEGY'
    INSTRUMENT = 'INSTRUMENT'


class TimePeriodModel(BaseModel):
    name: str = Field(
        ..., description='Name or label for this period', examples=['Q1 2023']
    )
    startDate: str = Field(
        ..., description='Start date of the period', examples=['2023-01-01T00:00:00Z']
    )
    endDate: str = Field(
        ..., description='End date of the period', examples=['2023-03-31T23:59:59Z']
    )


class ComparisonDimension(BaseModel):
    id: str | None = Field(None, description='Dimension ID', examples=['pf-1'])
    name: str | None = Field(
        None,
        description='Human-readable name of the dimension',
        examples=['Main Portfolio'],
    )
    description: str | None = Field(
        None, description='Optional description', examples=['High risk tech stocks']
    )
    startDate: str | None = Field(
        None,
        description='Effective start date for data in this dimension',
        examples=['2023-01-01T00:00:00Z'],
    )
    endDate: str | None = Field(
        None,
        description='Effective end date for data in this dimension',
        examples=['2023-12-31T23:59:59Z'],
    )
    tradeCount: int | None = Field(
        None,
        description="Total number of trades included in this dimension's calculation",
        examples=[150],
    )
    metadata: dict[str, dict[str, Any]] | None = Field(
        None, description='Additional metadata', examples=[{'isArchived': False}]
    )


class ComparisonMetric(BaseModel):
    name: str | None = Field(
        None, description='Internal name of the metric', examples=['WIN_RATE']
    )
    displayName: str | None = Field(
        None, description='Display name of the metric', examples=['Win Rate (%)']
    )
    unit: str | None = Field(None, description='Unit of measurement', examples=['%'])
    values: dict[str, float] | None = Field(
        None,
        description='The calculated value for each dimension ID',
        examples=[{'pf-1': 65.5, 'pf-2': 42.0}],
    )
    percentChanges: dict[str, float] | None = Field(
        None,
        description='Percent change from the baseline (first dimension)',
        examples=[{'pf-2': -35.8}],
    )
    bestDimensionId: str | None = Field(
        None,
        description='The dimension ID that performed the best on this metric',
        examples=['pf-1'],
    )
    worstDimensionId: str | None = Field(
        None,
        description='The dimension ID that performed the worst on this metric',
        examples=['pf-2'],
    )
    average: float | None = Field(
        None, description='Average value across all dimensions', examples=[53.75]
    )
    median: float | None = Field(
        None, description='Median value across all dimensions', examples=[53.75]
    )


class ComparisonResponse(BaseModel):
    comparisonId: str | None = Field(
        None,
        description='Unique identifier of this generated comparison report',
        examples=['comp-887766'],
    )
    userId: str | None = Field(
        None, description='User ID who requested the comparison', examples=['usr-123']
    )
    comparisonType: str | None = Field(
        None, description='Type of comparison performed', examples=['PORTFOLIO']
    )
    dimensions: list[ComparisonDimension] | None = Field(
        None, description='List of dimensions (entities) that were compared'
    )
    metrics: list[ComparisonMetric] | None = Field(
        None, description='List of calculated metrics across the dimensions'
    )
    additionalData: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Any additional unstructured data or chart configurations',
        examples=[{'chartType': 'spider'}],
    )
    generatedAt: str | None = Field(
        None,
        description='Timestamp when the comparison was generated',
        examples=['2023-11-15T10:30:00Z'],
    )


class SortObject(BaseModel):
    empty: bool | None = None
    sorted: bool | None = None
    unsorted: bool | None = None


class BulkDeleteRequest(BaseModel):
    filterIds: list[str]


class BulkDeleteResponse(BaseModel):
    deletedCount: int | None = Field(
        None, description='Number of items successfully deleted', examples=[2]
    )
    totalRequested: int | None = Field(
        None, description='Total number of items requested for deletion', examples=[2]
    )
    message: str | None = Field(
        None, description='Status message', examples=['Successfully deleted 2 items.']
    )


class TradeDetails(BaseModel):
    tradeId: str | None = None
    portfolioId: str | None = None
    instrumentInfo: InstrumentInfo | None = None
    symbol: str | None = None
    strategy: str | None = None
    status: Status | None = None
    tradePositionType: TradePositionType | None = None
    entryInfo: EntryExitInfo | None = None
    exitInfo: EntryExitInfo | None = None
    currentPrice: float | None = None
    metrics: TradeMetrics | None = None
    tradeExecutions: list[TradeModel] | None = None
    notes: str | None = None
    tags: list[str] | None = None
    userId: str | None = None
    attachments: list[Attachment] | None = None
    psychologyData: TradePsychologyData | None = None
    entryReasoning: TradeEntryExistReasoning | None = None
    exitReasoning: TradeEntryExistReasoning | None = None


class JournalTemplateRequest(BaseModel):
    name: str = Field(
        ...,
        description='Name of the journal template',
        examples=['Options Strategy Template'],
    )
    description: str | None = Field(
        None,
        description='Detailed description of what the template is used for',
        examples=['Template used for tracking advanced multi-leg options strategies'],
    )
    category: Category
    fields: list[TemplateFieldRequest] | None = Field(
        None, description='List of custom fields configured for this template'
    )
    isSystemTemplate: bool | None = Field(
        None,
        description='Indicates whether this is a default system template',
        examples=[False],
    )
    isRecommended: bool | None = Field(
        None,
        description='Indicates whether this template is recommended for users',
        examples=[True],
    )
    createdBy: str = Field(
        ..., description='User ID of the creator', examples=['usr-889912']
    )
    tags: list[str] | None = Field(
        None,
        description='Tags associated with this template for easy discovery',
        examples=[['Options', 'Iron Condor', 'High Risk']],
    )
    thumbnailUrl: str | None = Field(
        None,
        description='URL to a thumbnail image representing the template',
        examples=['https://example.com/thumbnails/options-template.png'],
    )


class JournalTemplateResponse(BaseModel):
    id: str | None = Field(
        None, description='Unique identifier of the template', examples=['tmpl-12345']
    )
    name: str | None = Field(
        None,
        description='Name of the journal template',
        examples=['Options Strategy Template'],
    )
    description: str | None = Field(
        None,
        description='Detailed description of what the template is used for',
        examples=['Template used for tracking advanced multi-leg options strategies'],
    )
    category: Category | None = None
    fields: list[TemplateFieldResponse] | None = Field(
        None, description='List of custom fields configured for this template'
    )
    isSystemTemplate: bool | None = Field(
        None,
        description='Indicates whether this is a default system template',
        examples=[False],
    )
    isRecommended: bool | None = Field(
        None,
        description='Indicates whether this template is recommended for users',
        examples=[True],
    )
    usageCount: int | None = Field(
        None, description='Number of times this template has been used', examples=[1250]
    )
    createdBy: str | None = Field(
        None, description='User ID of the creator', examples=['usr-889912']
    )
    isFavorite: bool | None = Field(
        None,
        description='Indicates if the currently authenticated user has favorited this template',
        examples=[True],
    )
    tags: list[str] | None = Field(
        None,
        description='Tags associated with this template for easy discovery',
        examples=[['Options', 'Iron Condor', 'High Risk']],
    )
    thumbnailUrl: str | None = Field(
        None,
        description='URL to a thumbnail image representing the template',
        examples=['https://example.com/thumbnails/options-template.png'],
    )
    createdAt: AwareDatetime | None = Field(
        None, description='Timestamp when the template was created'
    )
    updatedAt: AwareDatetime | None = Field(
        None, description='Timestamp when the template was last updated'
    )


class FavoriteFilterRequest(BaseModel):
    name: str
    description: str | None = None
    filterConfig: MetricsFilterConfig
    default: bool | None = None


class FilterTradeDetailsResponse(BaseModel):
    trades: list[TradeDetails] | None = Field(
        None, description='List of filtered trade details'
    )
    totalCount: int | None = Field(
        None, description='Total number of trades matching the filter'
    )
    appliedFilterName: str | None = Field(
        None, description='Applied filter name (if using favorite filter)'
    )
    filterSummary: FilterSummary | None = None
    page: int | None = Field(None, description='Current page number (0-based)')
    size: int | None = Field(None, description='Page size')
    totalPages: int | None = Field(None, description='Total number of pages')
    isFirst: bool | None = Field(None, description='Whether this is the first page')
    isLast: bool | None = Field(None, description='Whether this is the last page')


class AssetAllocation(BaseModel):
    assetClass: AssetClass | None = None
    currentPercentage: float | None = Field(
        None,
        description='Current percentage allocation of this asset class in the portfolio',
        examples=[45.5],
    )
    targetPercentage: float | None = Field(
        None, description='Target or ideal percentage allocation', examples=[50.0]
    )
    variance: float | None = Field(
        None,
        description='Variance between current and target allocation',
        examples=[-4.5],
    )


class TradeSummary(BaseModel):
    id: str | None = None
    userId: str | None = None
    name: str | None = None
    description: str | None = None
    ownerId: str | None = None
    active: bool | None = None
    currency: str | None = None
    startDate: AwareDatetime | None = None
    endDate: AwareDatetime | None = None
    createdDate: AwareDatetime | None = None
    lastUpdatedDate: AwareDatetime | None = None
    basicMetrics: PortfolioMetrics | None = None
    portfolioIds: list[str] | None = None
    totalTradeCount: int | None = None
    winningTradeCount: int | None = None
    losingTradeCount: int | None = None
    totalProfitLoss: float | None = None
    winRate: float | None = None
    averageHoldingTime: float | None = None
    averagePositionSize: float | None = None
    detailedMetricsId: str | None = None
    tradeDetails: list[TradeDetails] | None = None
    winningTrades: list[TradeDetails] | None = None
    losingTrades: list[TradeDetails] | None = None
    performanceMetrics: PerformanceMetrics | None = None
    riskMetrics: RiskMetrics | None = None
    distributionMetrics: TradeDistributionMetrics | None = None
    timingMetrics: TradeTimingMetrics | None = None
    strategyMetrics: dict[str, StrategyPerformanceMetrics] | None = None
    patternMetrics: TradePatternMetrics | None = None
    tradingFeedback: TradingFeedback | None = None
    maxDrawdown: float | None = None
    sharpeRatio: float | None = None
    sortinoRatio: float | None = None
    assetAllocations: list[AssetAllocation] | None = None
    tags: list[str] | None = None


class DashboardPreferencesRequest(BaseModel):
    defaultMetricTypes: list[str] = Field(
        ...,
        description='Default metric types to display on the dashboard',
        examples=[['PROFIT_LOSS', 'WIN_RATE', 'RISK_REWARD']],
    )
    favoritePortfolioIds: list[str] | None = Field(
        None,
        description='List of favorite portfolio IDs to show by default',
        examples=[['PF-100', 'PF-200']],
    )
    defaultTimeRange: str | None = Field(
        None,
        description='Default time range selection (DAILY, WEEKLY, MONTHLY, QUARTERLY, YEARLY, CUSTOM)',
        examples=['LAST_30_DAYS'],
    )
    customDaysRange: int | None = Field(
        None,
        description='Custom days range if defaultTimeRange is CUSTOM',
        examples=[45],
    )
    showProfitLossChart: bool | None = Field(
        None,
        description='Toggle to show or hide the Profit/Loss chart',
        examples=[True],
    )
    showWinRateChart: bool | None = Field(
        None, description='Toggle to show or hide the Win Rate chart', examples=[True]
    )
    showTradeFrequencyChart: bool | None = Field(
        None,
        description='Toggle to show or hide the Trade Frequency chart',
        examples=[False],
    )
    showInstrumentDistributionChart: bool | None = Field(
        None,
        description='Toggle to show or hide the Instrument Distribution chart',
        examples=[True],
    )
    widgetLayout: WidgetLayout | None = None
    additionalCharts: dict[str, bool] | None = Field(
        None,
        description='Map of additional custom charts and their visibility status',
        examples=[{'drawdownChart': True, 'heatMap': False}],
    )


class MetricsFilterRequest(BaseModel):
    portfolioIds: list[str] = Field(
        ...,
        description='Portfolio IDs to include in metrics calculation',
        examples=[['PF-100', 'PF-200']],
    )
    dateRange: DateRangeFilter | None = None
    timePeriod: TimePeriod | None = Field(
        None,
        description='Predefined time period for quick date range selection',
        examples=['LAST_30_DAYS'],
    )
    metricTypes: list[str] | None = Field(
        None,
        description='Types of metrics to include in the response',
        examples=[['PERFORMANCE', 'RISK']],
    )
    instruments: list[str] | None = Field(
        None,
        description='Filter trades by specific instruments',
        examples=[['AAPL', 'TSLA']],
    )
    instrumentFilters: InstrumentFilterCriteria | None = None
    tradeCharacteristics: TradeCharacteristicsFilter | None = None
    profitLossFilters: ProfitLossFilter | None = None
    groupBy: list[str] | None = Field(
        None,
        description='Group metrics by specific dimensions',
        examples=[['STRATEGY', 'SYMBOL']],
    )
    includeTradeDetails: bool | None = Field(
        False,
        description='Flag to include trade details in the response',
        examples=[True],
    )
    customFilters: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Additional custom filters as key-value pairs',
        examples=[{'customTag': 'value1'}],
    )


class MetricsResponse(BaseModel):
    portfolioIds: list[str] | None = Field(
        None,
        description='List of portfolio IDs included in the metrics calculation',
        examples=[['PF-100']],
    )
    startDate: date | None = Field(
        None,
        description='Start date of the metrics calculation period',
        examples=['2023-01-01'],
    )
    endDate: date | None = Field(
        None,
        description='End date of the metrics calculation period',
        examples=['2023-12-31'],
    )
    totalTradesCount: int | None = Field(
        None,
        description='Total number of trades included in the metrics calculation',
        examples=[150],
    )
    tradeDetails: list[TradeDetails] | None = Field(
        None, description='List of trade details (included only if requested in filter)'
    )
    performanceMetrics: PerformanceMetrics | None = None
    riskMetrics: RiskMetrics | None = None
    distributionMetrics: TradeDistributionMetrics | None = None
    timingMetrics: TradeTimingMetrics | None = None
    patternMetrics: TradePatternMetrics | None = None
    strategyMetrics: dict[str, StrategyPerformanceMetrics] | None = Field(
        None,
        description='Strategy-specific metrics, keyed by strategy name',
        examples=['{"MACD-Cross": {...}}'],
    )
    groupedMetrics: dict[str, dict[str, dict[str, Any]]] | None = Field(
        None,
        description='Metrics grouped by specific requested dimensions (e.g., by SYMBOL or DAY_OF_WEEK)',
    )
    metadata: dict[str, dict[str, Any]] | None = Field(
        None,
        description='Metadata about the metrics calculation process (e.g., execution time, cached status)',
        examples=[{'executionTimeMs': 45}],
    )


class ProfitLossHeatmapData(BaseModel):
    granularityType: GranularityType | None = None
    periodData: list[PeriodProfitLossData] | None = None
    totalProfitLoss: float | None = None
    winCount: int | None = None
    lossCount: int | None = None
    winRate: float | None = None
    tradeDetails: list[TradeDetails] | None = None
    winTrades: list[TradeDetails] | None = None
    lossTrades: list[TradeDetails] | None = None


class ComparisonRequest(BaseModel):
    comparisonType: ComparisonType = Field(
        ..., description='Type of comparison to perform', examples=['PORTFOLIO']
    )
    portfolioIds: list[str] | None = None
    timePeriods: list[TimePeriodModel] | None = Field(
        None,
        description='List of custom time periods to compare (if comparisonType is TIME_PERIOD)',
    )
    strategies: list[str] | None = None
    instruments: list[str] | None = None
    startDate: str | None = Field(
        None,
        description='Global start date filter for the comparison',
        examples=['2023-01-01T00:00:00Z'],
    )
    endDate: str | None = Field(
        None,
        description='Global end date filter for the comparison',
        examples=['2023-12-31T23:59:59Z'],
    )
    includedMetrics: list[str] | None = None
    normalizeResults: bool | None = Field(
        None,
        description='Whether to normalize the results for fair comparison across different scales',
        examples=[True],
    )


class PageableObject(BaseModel):
    offset: int | None = None
    sort: SortObject | None = None
    pageSize: int | None = None
    pageNumber: int | None = None
    paged: bool | None = None
    unpaged: bool | None = None


class TradeSummaryDetailed(BaseModel):
    id: str | None = None
    tradeSummaryBasicId: str | None = None
    tradeDetails: list[TradeDetails] | None = None
    winningTrades: list[TradeDetails] | None = None
    losingTrades: list[TradeDetails] | None = None
    performanceMetrics: PerformanceMetrics | None = None
    riskMetrics: RiskMetrics | None = None
    distributionMetrics: TradeDistributionMetrics | None = None
    timingMetrics: TradeTimingMetrics | None = None
    strategyMetrics: dict[str, StrategyPerformanceMetrics] | None = None
    patternMetrics: TradePatternMetrics | None = None
    tradingFeedback: TradingFeedback | None = None
    lastCalculatedTimestamp: AwareDatetime | None = None


class TradeSummaryBasic(BaseModel):
    id: str | None = None
    userId: str | None = None
    name: str | None = None
    description: str | None = None
    ownerId: str | None = None
    active: bool | None = None
    currency: str | None = None
    startDate: AwareDatetime | None = None
    endDate: AwareDatetime | None = None
    createdDate: AwareDatetime | None = None
    lastUpdatedDate: AwareDatetime | None = None
    basicMetrics: PortfolioMetrics | None = None
    portfolioIds: list[str] | None = None
    tradeDetails: list[TradeDetails] | None = None
    totalTradeCount: int | None = None
    winningTradeCount: int | None = None
    losingTradeCount: int | None = None
    totalProfitLoss: float | None = None
    winRate: float | None = None
    averageHoldingTime: float | None = None
    averagePositionSize: float | None = None
    detailedMetricsId: str | None = None


class PortfolioModel(BaseModel):
    portfolioId: str | None = Field(
        None, description='Unique identifier of the portfolio', examples=['pf-443322']
    )
    name: str | None = Field(
        None, description='Name of the portfolio', examples=['Tech Growth Fund']
    )
    description: str | None = Field(
        None,
        description='Description of the portfolio strategy',
        examples=['Aggressive growth focused on tech stocks'],
    )
    ownerId: str | None = Field(
        None, description='User ID of the portfolio owner', examples=['usr-8899']
    )
    active: bool | None = Field(
        None, description='Whether the portfolio is currently active', examples=[True]
    )
    currency: str | None = Field(
        None,
        description='Base currency of the portfolio (ISO 4217 code)',
        examples=['USD'],
    )
    initialCapital: float | None = Field(
        None, description='Initial capital deposited', examples=[50000.0]
    )
    currentCapital: float | None = Field(
        None,
        description='Current capital including all realized and unrealized PnL',
        examples=[65400.25],
    )
    createdDate: AwareDatetime | None = Field(
        None, description='Creation date', examples=['2023-01-01T10:00:00Z']
    )
    lastUpdatedDate: AwareDatetime | None = Field(
        None, description='Last update timestamp', examples=['2023-11-20T15:30:00Z']
    )
    metrics: PortfolioMetrics | None = None
    tradeIds: list[str] | None = None
    winningTradeIds: list[str] | None = None
    losingTradeIds: list[str] | None = None
    assetAllocations: list[AssetAllocation] | None = Field(
        None, description='Asset allocation breakdown'
    )


class PageTradeJournalEntryResponse(BaseModel):
    totalElements: int | None = None
    totalPages: int | None = None
    size: int | None = None
    content: list[TradeJournalEntryResponse] | None = None
    number: int | None = None
    sort: SortObject | None = None
    first: bool | None = None
    last: bool | None = None
    numberOfElements: int | None = None
    pageable: PageableObject | None = None
    empty: bool | None = None


class PageTradeDetails(BaseModel):
    totalElements: int | None = None
    totalPages: int | None = None
    size: int | None = None
    content: list[TradeDetails] | None = None
    number: int | None = None
    sort: SortObject | None = None
    first: bool | None = None
    last: bool | None = None
    numberOfElements: int | None = None
    pageable: PageableObject | None = None
    empty: bool | None = None
