# generated by datamodel-codegen:
#   filename:  dummy_schema.json
#   timestamp: 2026-07-24T07:10:48+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class JournalTemplateCategory(Enum):
    DAILY_CHECKIN = 'DAILY_CHECKIN'
    PRE_MARKET = 'PRE_MARKET'
    POST_MARKET = 'POST_MARKET'
    TRADE_RECAP = 'TRADE_RECAP'


class TestPayload(BaseModel):
    category: JournalTemplateCategory | None = None
