@echo off
setlocal
set "REPO_ROOT=%~dp0"
set "REPO_ROOT=%REPO_ROOT:~0,-1%"
REM Bidirectional env mapping: packages vars <-> actor/token (either pair is enough).
if "%GITHUB_PACKAGES_USERNAME%"=="" set "GITHUB_PACKAGES_USERNAME=%GITHUB_ACTOR%"
if "%GITHUB_PACKAGES_TOKEN%"=="" set "GITHUB_PACKAGES_TOKEN=%GITHUB_TOKEN%"
if "%GITHUB_PACKAGES_TOKEN%"=="" set "GITHUB_PACKAGES_TOKEN=%GHCR_TOKEN%"
if "%GITHUB_ACTOR%"=="" set "GITHUB_ACTOR=%GITHUB_PACKAGES_USERNAME%"
if "%GITHUB_TOKEN%"=="" set "GITHUB_TOKEN=%GITHUB_PACKAGES_TOKEN%"
docker run --rm -v "%REPO_ROOT%:/app" -v "%USERPROFILE%\.m2:/root/.m2" -e GHCR_TOKEN="%GHCR_TOKEN%" -e GITHUB_TOKEN="%GITHUB_TOKEN%" -e GITHUB_ACTOR="%GITHUB_ACTOR%" -e GITHUB_PACKAGES_USERNAME="%GITHUB_PACKAGES_USERNAME%" -e GITHUB_PACKAGES_TOKEN="%GITHUB_PACKAGES_TOKEN%" -w /app maven:3.9-eclipse-temurin-17 mvn -s /app/settings.xml %*
