apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "am-market-data.fullname" . }}-config
  labels:
    {{- include "am-market-data.labels" . | nindent 4 }}
data:
  # Spring Profile
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}
  TZ: Asia/Kolkata

  # Database Configuration
  POSTGRES_URL: jdbc:postgresql://{{ .Values.postgresql.fullname }}:{{ .Values.postgresql.primary.service.port }}
  POSTGRES_DATABASE: {{ .Values.postgresql.auth.database }}
  POSTGRES_USERNAME: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}

  # InfluxDB Configuration
  INFLUXDB_URL: {{ .Values.influxdb.url }}
  INFLUXDB_ORG: {{ .Values.influxdb.auth.org }}
  INFLUXDB_BUCKET: {{ .Values.influxdb.auth.bucket }}
  INFLUXDB_TOKEN: {{ .Values.influxdb.auth.token }}

  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers }}
  KAFKA_ZOOKEEPER_CONNECT: {{ .Values.kafka.zookeeper.connect }}
  KAFKA_CONSUMER_GROUP_ID: {{ .Values.kafka.config.consumerGroupId }}
  KAFKA_CONSUMER_AUTO_OFFSET_RESET: {{ .Values.kafka.config.autoOffsetReset }}
  KAFKA_TOPICS_STOCK_PRICE: {{ .Values.kafka.config.topics.stockPrice }}
  KAFKA_TOPICS_NSE_INDICES: {{ .Values.kafka.config.topics.nseIndices }}
  KAFKA_TOPICS_NSE_ETF: {{ .Values.kafka.config.topics.nseEtf }}

  # Market Data Configuration
  MARKET_DATA_MAX_RETRIES: "{{ .Values.config.marketData.maxRetries }}"
  MARKET_DATA_RETRY_DELAY_MS: "{{ .Values.config.marketData.retryDelayMs }}"
  MARKET_DATA_THREAD_POOL_SIZE: "{{ .Values.config.marketData.threadPoolSize }}"
  MARKET_DATA_THREAD_QUEUE_CAPACITY: "{{ .Values.config.marketData.threadQueueCapacity }}"
  MARKET_DATA_MAX_AGE_MINUTES: "{{ .Values.config.marketData.maxAgeMinutes }}"

  # Upstox Configuration
  UPSTOX_API_BASE_URL: {{ .Values.upstox.auth.baseUrl }}
  UPSTOX_REDIRECT_URI: {{ .Values.upstox.auth.redirectUri }}

  # Metrics Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,metrics,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_METRICS_TAGS_APPLICATION: market-data-{{ .Values.environment }}
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "{{ .Values.monitoring.prometheus.scrape }}"
