apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "am-trade-management.fullname" . }}-config
  labels:
    {{- include "am-trade-management.labels" . | nindent 4 }}
data:
  application.yaml: |
    spring:
      profiles:
        active: {{ .Values.env.profile | default "preprod" }}
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
