apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "am-trade-management.fullname" . }}
  labels:
    {{- include "am-trade-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "am-trade-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "am-trade-management.selectorLabels" . | nindent 8 }}
        version: {{ .Values.deployment.version | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.profile | default "preprod" }}
            - name: TZ
              value: "Asia/Kolkata"
