{{- if .Values.ingress.enabled -}}
{{- $fullName := printf "%s-ingress" (include "am-trade-management.fullname" .) -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
        {{- include "am-trade-management.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
