replicaCount: 2

spring:
  profiles:
    active: preprod
  mongodb:
    uri: "mongodb://trade-db-user:T0kenS3cr3t@mongodb-cluster.am-apps-preprod.svc.cluster.local:27017/portfolio"
  kafka:
    bootstrapServers: "kafka-cluster.am-apps-preprod.svc.cluster.local:9092"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: trade-preprod.amportfolio.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
