replicaCount: 4

spring:
  profiles:
    active: prod
  mongodb:
    uri: "mongodb://trade-db-user:P0WerFuLCr3ds@mongodb-cluster.am-apps-prod.svc.cluster.local:27017/portfolio"
    database: "portfolio"
  kafka:
    bootstrapServers: "kafka-cluster.am-apps-prod.svc.cluster.local:9092"
    tradeTopic: "am-trade"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  hosts:
    - host: trade.amportfolio.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi
