spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:password123@localhost:27017/trade_management?authSource=admin&directConnection=true}
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security:
        protocol: PLAINTEXT  # <--- THIS IS THE MAGIC LINE
    consumer:
      auto-offset-reset: earliest

management:
  health:
    mongo:
      enabled: false
    kafka:
      enabled: false

app:
  kafka:
    enabled: true
