# Common configuration shared across all environments

# MongoDB common configuration
spring:
  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

# Resilience4j common configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.io.IOException
          - java.net.SocketTimeoutException

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: am.trade.api.controller

# Server configuration
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048

app:
  persistence:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/portfolio?authSource=admin&retryWrites=false
      database: portfolio
# Application specific common settings
am:
  trade:
    kafka:
      bootstrap-servers: kafka.dev.svc.cluster.local:9092
      consumer-group-id: ${KAFKA_CONSUMER_GROUP_ID:am-trade-group}
      trade-events-topic: ${KAFKA_TOPICS_TRADE_EVENTS:am-trade-events}
      order-events-topic: ${KAFKA_TOPICS_ORDER_EVENTS:am-order-events}
      retries: 3
      retry-backoff-ms: 1000
      max-poll-records: 500
      max-poll-interval-ms: 300000
      session-timeout-ms: 10000
      heartbeat-interval-ms: 3000
      max-in-flight-requests-per-connection: 5
      enable-auto-commit: false
      auto-offset-reset: latest
      properties:
        security-protocol: SASL_SSL
        sasl-mechanism: PLAIN
        sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaUser" password="kafkaPassword123!";
    api:
      enabled: true
    common:
      enabled: true
      date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    services:
      enabled: true
      retry:
        max-attempts: 3
        backoff-multiplier: 2.0
      circuit-breaker:
        failure-threshold: 40
        reset-timeout-seconds: 60
    dashboard:
      enabled: true
      metrics:
        collection-interval-seconds: 60
        retention-days: 30
