# Common configuration shared across all environments

# Resilience4j common configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500
        retryExceptions:
          - org.springframework.dao.DataAccessException
          - java.io.IOException
          - java.net.SocketTimeoutException

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: am.trade.api.controller

# Server configuration
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 2048
