# Production environment configuration

# MongoDB production configuration
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: trade_management_prod
      ssl:
        enabled: true
        invalid-hostname-allowed: false
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
        invalid-hostname-allowed: false
  cache:
    type: redis

# Logging configuration for production
logging:
  level:
    root: WARN
    am.trade: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.web: WARN
  file:
    name: /var/log/am-trade/application-prod.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Production server configuration
server:
  port: 8080
  tomcat:
    max-threads: 400
    max-connections: 20000
    accept-count: 200
    connection-timeout: 3000
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/plain

# Actuator configuration for production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
