# Kafka Topics
am:
  trade:
    kafka:
      bootstrap-servers: kafka.dev.svc.cluster.local:9092
      consumer-group-id: ${KAFKA_CONSUMER_GROUP_ID:am-trade-group}
      trade-events-topic: ${KAFKA_TOPICS_TRADE_EVENTS:am-trade-events}
      order-events-topic: ${KAFKA_TOPICS_ORDER_EVENTS:am-order-events}
      retries: 3
      retry-backoff-ms: 1000
      max-poll-records: 500
      max-poll-interval-ms: 300000
      session-timeout-ms: 10000
      heartbeat-interval-ms: 3000
      max-in-flight-requests-per-connection: 5
      enable-auto-commit: false
      auto-offset-reset: latest
      properties:
        security-protocol: SASL_SSL
        sasl-mechanism: PLAIN
        sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaUser" password="kafkaPassword123!";
