spring:
  application:
    name: am-trade-management
  config:
    import:
      - classpath:application-common.yml

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      validate-group-membership: false
      group:
        readiness:
          include: diskSpace
          exclude: mongodb,redis,kafka
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    mongo:
      enabled: false

# Logging configuration
logging:
  level:
    root: INFO
    am.trade: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO
