
# MONGODB_URI: ${MONGODB_URI}
# MONGODB_DATABASE: ${MONGODB_DATABASE}

# KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
# KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
# KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
# KAFKA_SASL_JAAS_CONFIG: ${KAFKA_SASL_JAAS_CONFIG}

# Logging configuration for pre-production
logging:
  level:
    root: INFO
    am.trade: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO
  file:
    name: /var/log/am-trade/application-preprod.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Pre-production server configuration
server:
  port: 8080
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100
    connection-timeout: 5000

# Pre-production-specific application settings
am:
  trade:
    services:
      retry:
        max-attempts: 3
        backoff-multiplier: 1.5
      circuit-breaker:
        failure-threshold: 50
        reset-timeout-seconds: 30
    dashboard:
      metrics:
        collection-interval-seconds: 60
        retention-days: 90
