vault:
  secretPaths:
    auth:
      mappings:
        JWT_SECRET: "JWT_SECRET"
        INTERNAL_SECRET_KEY: "SECRET_KEY"
        SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET_KEY: "JWT_SECRET"
    market-data:
      mappings:
        AM_MARKET_DATA_API_URL: "url"
    mongo:
      mappings:
        MONGODB_URI: "url"
        SPRING_DATA_MONGODB_URI: "url"
    kafka:
      mappings:
        KAFKA_BOOTSTRAP_SERVERS: "bootstrap_servers"
        SPRING_KAFKA_BOOTSTRAP_SERVERS: "bootstrap_servers"
        KAFKA_SASL_JAAS_CONFIG: "__jaas__"
        KAFKA_SASL_USERNAME: "username"
        KAFKA_SASL_PASSWORD: "password"
    redis:
      mappings:
        SPRING_DATA_REDIS_HOST: "host"
        SPRING_DATA_REDIS_PASSWORD: "password"
        SPRING_DATA_REDIS_PORT: "port"
