name: AM Trade Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "test/**", "fix/**", "hotfix/**"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  publish:
    name: Publish AM Trade Management
    permissions:
      contents: write
      packages: write
    uses: AM-Portfolio/am-pipelines/.github/workflows/central-build-publish-contabo.yml@main
    with:
      language: 'java'
      working_directory: '.'
      image_name: 'am-trade-management-service'
      build_context: '.'
    secrets: inherit
