name: AM Trade Publish

on:
  push:
    branches: ["main", "develop", "feature/**", "test/**", "fix/**", "hotfix/**"]
    paths:
      - './**'
      - '.github/workflows/am-trade-publish.yml'
  pull_request:
    branches: ["main", "develop"]
    paths:
      - './**'
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/central-build-publish-no-deploy.yml
    with:
      language: 'java'
      working_directory: '.'
      image_name: 'am-trade-management-service'
      build_context: '.'
      skip_secrets_scan: true
    secrets: inherit
