name: Deployment

on:
  # Manual deployment with environment selection
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod
      image_tag:
        description: 'Docker image tag to deploy (leave empty for latest build)'
        required: false
        type: string
  
  # Called by docker-build workflow
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/am-trade-management-service
  HELM_CHART_PATH: ./helm/am-trade-management

jobs:
  # Deploy to the selected environment
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    env:
      # Set environment based on workflow_dispatch input or default to preprod for workflow_call
      ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'preprod' }}
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set environment-specific variables
      - name: Set environment variables
        id: set-vars
        run: |
          # Set environment-specific variables
          if [[ "${{ env.ENVIRONMENT }}" == "prod" ]]; then
            echo "RESOURCE_GROUP=am-investing" >> $GITHUB_ENV
            echo "CLUSTER_NAME=am-np-west" >> $GITHUB_ENV
            echo "NAMESPACE=dev" >> $GITHUB_ENV
            echo "Deploying to PRODUCTION environment"
          else
            echo "RESOURCE_GROUP=am-investing" >> $GITHUB_ENV
            echo "CLUSTER_NAME=am-np-west" >> $GITHUB_ENV
            echo "NAMESPACE=dev" >> $GITHUB_ENV
            echo "Deploying to PRE-PRODUCTION environment"
          fi
      
      # Get image tag - either from workflow_dispatch input or workflow_call input
      - name: Get image tag
        id: get-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.image_tag }}" != "" ]]; then
            # Use the manually provided tag
            echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
            echo "Using manually provided image tag: ${{ github.event.inputs.image_tag }}"
          elif [[ "${{ github.event_name }}" == "workflow_call" ]]; then
            # Use the tag passed from docker-build workflow
            echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV
            echo "Using image tag from workflow_call: ${{ inputs.image_tag }}"
          else
            # Default tag if none provided
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "Using default image tag: latest"
          fi
      
    # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
      
      # Setup Helm
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'
      
      # Deploy to AKS using Helm
      - name: Deploy to AKS
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          
          # Echo image and environment details for logging
          echo "Deploying image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Resource Group: ${{ env.RESOURCE_GROUP }}"
          echo "Cluster: ${{ env.CLUSTER_NAME }}"
          echo "Namespace: ${{ env.NAMESPACE }}"
          
          # Deploy using Helm with the appropriate values file
          helm upgrade --install am-trade-management-service ${{ env.HELM_CHART_PATH }} \
            --namespace ${{ env.NAMESPACE }} \
            -f ${{ env.HELM_CHART_PATH }}/values/${{ env.ENVIRONMENT }}.yaml \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set deployment.version="${{ env.IMAGE_TAG }}" \
            --wait --timeout 5m
      
      # Verify deployment
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/am-trade-management-service -n ${{ env.NAMESPACE }}
          echo "Deployment to ${{ env.ENVIRONMENT }} completed successfully!"
